export type ThemeToken =
  | "--surface-base"
  | "--surface-elevated"
  | "--surface-overlay"
  | "--text-primary"
  | "--text-secondary"
  | "--text-muted"
  | "--accent"
  | "--accent-hover"
  | "--border-subtle"
  | "--border-default"
  | "--status-pass"
  | "--status-warn"
  | "--status-fail"
  | "--status-pass-bg"
  | "--status-warn-bg"
  | "--status-fail-bg";
